# Generated by Django 2.0.3 on 2020-05-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta',
            old_name='price',
            new_name='small',
        ),
        migrations.RenameField(
            model_name='salads',
            old_name='price',
            new_name='small',
        ),
        migrations.AddField(
            model_name='pasta',
            name='large',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4),
        ),
        migrations.AddField(
            model_name='salads',
            name='large',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4),
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='category',
            field=models.CharField(default='Dinner Platter', max_length=64),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='category',
            field=models.CharField(default='Pasta', max_length=64),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='category',
            field=models.CharField(default='Regular Pizza', max_length=64),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='category',
            field=models.CharField(default='Sicilian Pizza', max_length=64),
        ),
        migrations.AlterField(
            model_name='subs',
            name='category',
            field=models.CharField(default='Subs', max_length=64),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='category',
            field=models.CharField(default='Toppings', max_length=64),
        ),
    ]
